Update Log driver example to xstream
cyclejs/cyclejs.github.io pull request #66
Opened 2016-10-23 20:55 UTC by SteveALee

2016-10-23 20:57 UTC, mightyiam requested changes
Just my two cents.

2016-10-23 20:57 UTC, mightyiam commented on _posts/2015-01-23-drivers.md
> +  log: msg$ => { msg$.addListener({next: msg => console.log(msg)}) }
In xstream, if I remember correctly, you must provide all three, `next`, `error` and `complete` properties.

2016-10-23 20:58 UTC, SteveALee commented on _posts/2015-01-23-drivers.md
> +  log: msg$ => { msg$.addListener({next: msg => console.log(msg)}) }
@staltz recently said on Gitter that only next is required. I've not double checked the code though. Thanks for comment.

2016-10-24 08:47 UTC, staltz commented
Correct. Thanks @SteveALee !

2016-10-24 08:48 UTC, merged